### ISSUE TITLE
Possible to upload other content types than mentioned

### ISSUE THREAD

**Issue by maethu** [4teamwork/django-eventary#156]
Check:
<img width="1068" alt="screen shot 2017-05-19 at 15 11 54" src="https://cloud.githubusercontent.com/assets/437933/26249146/90ad3c42-3ca5-11e7-818f-650501f9f368.png">

**Comment by tarnap** [comment]
Gugg ees... es validiert!

![file format](https://cloud.githubusercontent.com/assets/194114/26251597/1755079a-3cae-11e7-834c-a1b8194fcb61.gif)
